import { AlertTriangle, Wifi, WifiOff } from "lucide-react";
import { cn } from "../lib/utils";
import { MODEL_DISCLAIMER } from "../data/mockAdminData";

/** Amber disclaimer banner shown on all ML prediction pages */
export function DisclaimerBanner({ className }: { className?: string }) {
  return (
    <div
      className={cn(
        "flex items-start gap-3 rounded-xl border border-amber-500/40 bg-amber-500/10 p-3",
        className
      )}
    >
      <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-500" />
      <div>
        <p className="text-sm font-medium text-foreground">{MODEL_DISCLAIMER}</p>
        <p className="mt-0.5 text-xs text-muted-foreground">
          soil_moisture_pct and ndvi_index are placeholder estimates until satellite data
          integration. Crop Vital Scores are generated by the{" "}
          <span className="font-mono">crop_vital</span> ML model.
        </p>
      </div>
    </div>
  );
}

/** Small badge showing whether the backend (port 8000) is connected */
export function DataSourceBadge({ live }: { live: boolean }) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium",
        live
          ? "bg-emerald-500/10 text-emerald-500"
          : "bg-muted text-muted-foreground"
      )}
      title={
        live
          ? "Connected to backend API on port 8000"
          : "Backend offline — showing local mock data (demo mode)"
      }
    >
      {live ? (
        <Wifi className="h-3 w-3" />
      ) : (
        <WifiOff className="h-3 w-3" />
      )}
      {live ? "Live API" : "Demo Data"}
    </span>
  );
}
